[package]
name = "seelater"
version = "0.1.0"
authors = ["Maurizio Crocci <mbcrocci@gmail.com>"]

[dependencies]
clap = "~2.27.0"
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0"
dirs = "1.0.4"
